# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CityDevs
email: hola@citydevs.mx
description: CityDevs somos un colectivo multidisciplinario enfocado en el desarrollo de tecnología cívica, la apertura de datos y mejorar la comunicación entre ciudadanía y gobierno.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://citydevs.mx" # the base hostname & protocol for your site
twitter_username: citydevs
github_username:  citydevs

# Build settings
markdown: kramdown
